spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/communicate?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      password: qq2388286985
    password: qq2388286985
    url: jdbc:mysql://localhost:3306/communicate?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
logging:
  level:
    org:
      springframework:
        security: debug

    com:
      Lu:
        mapper: debug
        service: info
        controller: info
  config:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


